### ISSUE TITLE
Manually setting permissions on Android device

### ISSUE THREAD

**Issue by sleepingspy999** [D3VL/L3MON#41] opened 2020-02-05 14:28 UTC
Not sure if this is a bug or is default action.
Once apk installed on device have to change permissions manually.
Have issue your working on saying Java Not Installed ,but event log shows Error then Build sucess and build.s.apk is being created fine.
Everything works fine once permission have been set.
Great project thanks.

**Comment by Jack-Rogers** [comment] 2020-02-05 14:33
Nope, this is by design and is why the app takes you to the permissions pages by default.
The app is not meant to be installable automatically and is made to be provisioned by an authorized user of the device, aka, you can't install the payload by accident from a malicious user.

Duplicate of #40

**Closed by Jack-Rogers** 2020-02-05 14:33 UTC
Labels: bug
