### ISSUE TITLE
ERROR | Build Failed - Sign Command Failed 

### ISSUE THREAD

**Issue by harshraj6982** [D3VL/L3MON#30] opened 2020-01-23 14:31 UTC
23/01/2020, 14:21:50 => ERROR | Build Failed - Sign Command Failed - Command failed: java -jar "/root/Desktop/L3MON-v1.1.0/app/factory/sign.jar" "/root/Desktop/L3MON-v1.1.0/assets/webpublic/build.apk" Exception in thread "main" java.lang.NoClassDefFoundError: sun/misc/BASE64Encoder at s.Sign.addDigestsToManifest(Sign.java:108) at s.Sign.sign(Sign.java:454) at s.Sign.main(Sign.java:532) Caused by: java.lang.ClassNotFoundException: sun.misc.BASE64Encoder at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581) at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178) at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521) ... 3 more

**Comment by Jack-Rogers** [comment] 2020-01-23 18:40
A possible duplicate of issue #15 
Could you please run `java -version` and send back the output.

**Comment by harshraj6982** [comment] 2020-01-24 14:51
openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment (build 11.0.6+10-post-Debian-1)
OpenJDK 64-Bit Server VM (build 11.0.6+10-post-Debian-1, mixed mode, sharing)

**Closed** 2020-01-24 16:12 UTC

**Comment by Theblood** [comment] 2020-01-31 15:17
Try command  
`update-alternatives --config java` and select options version

>  /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java
