### ISSUE TITLE
Please add call record feature.

### ISSUE THREAD

**Issue by vijaykumar211** [D3VL/L3MON#49] opened 2020-02-14 10:38 UTC
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
App automatically record all incoming and outgoing calls.

**Describe alternatives you've considered**

**Additional context**

**Comment by Jack-Rogers** [comment] 2020-02-14 12:21
Duplicate of #35

**Closed by Jack-Rogers** 2020-02-14 12:21 UTC
Labels: Feature Request
